[flang-rt] Use std::numeric_limits::infinity (#178166)
#175373 introduces a divide-by-zero to create an infinity value, which
is undefined behavior in C++ (C++20 [expr.mul] §4), even when done at
compile-time. This cases flaky test fails with the flang-x86_64-windows
buildbot. Visual Studio 2026 refuses to compile it with error C2124.

Use `std::numeric_limits<float>::infinity()` instead.