Revert "[lldb-dap] Use protocol types for exceptioninfo" (#166161)
Reverts llvm/llvm-project#165858 due to failures on Arm 32-bit.

```
Traceback (most recent call last):
  File "/home/tcwg-buildbot/worker/lldb-arm-ubuntu/llvm-project/lldb/test/API/tools/lldb-dap/exception/TestDAP_exception.py", line 24, in test_stopped_description
    self.assertEqual(exceptionInfo["description"], "signal SIGABRT")
AssertionError: '\x01ignal SIGABRT' != 'signal SIGABRT'
- ignal SIGABRT
? ^
+ signal SIGABRT
? ^
```