Revert "[CI] Make premerge_advisor_explain write comments"
This reverts commit 1f8d5d46df48720973c8312447b1c9a0165213d4.

This was causing failures in some cases.

```
  + python /home/gha/actions-runner/_work/llvm-project/llvm-project/.ci/premerge_advisor_explain.py 1f8d5d46df48720973c8312447b1c9a0165213d4 0 *** 167018 /home/gha/actions-runner/_work/llvm-project/llvm-project/build/test-results.zst9icbo.xml /home/gha/actions-runner/_work/llvm-project/llvm-project/ninja.log
  Traceback (most recent call last):
    File "/home/gha/actions-runner/_work/llvm-project/llvm-project/.ci/premerge_advisor_explain.py", line 146, in <module>
      main(
    File "/home/gha/actions-runner/_work/llvm-project/llvm-project/.ci/premerge_advisor_explain.py", line 78, in main
      comment = get_comment(
                ^^^^^^^^^^^^
  TypeError: get_comment() missing 2 required positional arguments: 'pr_number' and 'body'
  Error: Process completed with exit code 1.
```

```
  Traceback (most recent call last):
    File "C:\_work\llvm-project\llvm-project\.ci\premerge_advisor_explain.py", line 23, in <module>
      def get_comment_id(platform: str, pr: github.PullRequest.PullRequest) -> int | None:
  TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```